/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paintAbstract.testPaint;

import java.awt.Color;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import paintAbstract.*;

/**
 *
 * @author Sajjad
 */
public class MyPaint extends javax.swing.JFrame {

    ShapeTypes curShape = ShapeTypes.Line;
    ActionType curAction = ActionType.Draw;
    Color curBorderColor = Color.MAGENTA;
    Color curFillColor = Color.cyan;
    Point p1, p2, p3;
    ArrayList<Point> pArr;
    PaintingArea myArea;

    /**
     * Creates new form MyPaint
     */
    public MyPaint() {
        initComponents();
        myArea = new PaintingArea(paintPanel.getGraphics(), paintPanel.getWidth(), paintPanel.getHeight());
        pArr = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Parsa Es
    private void initComponents() {
        paintPanel = new JPanel();
        btnLine = new JButton();
        btnRect = new JButton();
        btnCircle = new JButton();
        btnMove = new JButton();
        btnErase = new JButton();
        chbIsFill = new JCheckBox();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //======== paintPanel ========
        {
            paintPanel.setBackground(Color.white);
            paintPanel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    paintPanelMouseClicked(e);
                }
            });
            paintPanel.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing. border .EmptyBorder ( 0
            , 0 ,0 , 0) ,  "JFor\u006dDesi\u0067ner \u0045valu\u0061tion" , javax. swing .border . TitledBorder. CENTER ,javax . swing. border .TitledBorder . BOTTOM
            , new java. awt .Font ( "Dia\u006cog", java .awt . Font. BOLD ,12 ) ,java . awt. Color .red ) ,
            paintPanel. getBorder () ) ); paintPanel. addPropertyChangeListener( new java. beans .PropertyChangeListener ( ){ @Override public void propertyChange (java . beans. PropertyChangeEvent e
            ) { if( "bord\u0065r" .equals ( e. getPropertyName () ) )throw new RuntimeException( ) ;} } );

            GroupLayout paintPanelLayout = new GroupLayout(paintPanel);
            paintPanel.setLayout(paintPanelLayout);
            paintPanelLayout.setHorizontalGroup(
                paintPanelLayout.createParallelGroup()
                    .addGap(0, 676, Short.MAX_VALUE)
            );
            paintPanelLayout.setVerticalGroup(
                paintPanelLayout.createParallelGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
            );
        }

        //---- btnLine ----
        btnLine.setText("Line");
        btnLine.addActionListener(e -> btnLineActionPerformed(e));

        //---- btnRect ----
        btnRect.setText("Recta");
        btnRect.addActionListener(e -> btnRectActionPerformed(e));

        //---- btnCircle ----
        btnCircle.setText("Circle");
        btnCircle.addActionListener(e -> btnCircleActionPerformed(e));

        //---- btnMove ----
        btnMove.setText("Move");
        btnMove.addActionListener(e -> btnMoveActionPerformed(e));

        //---- btnErase ----
        btnErase.setText("Erase");
        btnErase.addActionListener(e -> btnEraseActionPerformed(e));

        //---- chbIsFill ----
        chbIsFill.setText("Is Filled?");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCircle)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                    .addComponent(btnErase)
                                    .addComponent(btnMove)
                                    .addComponent(chbIsFill))))
                        .addComponent(btnRect, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnLine)))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paintPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(paintPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(btnLine)
                    .addGap(18, 18, 18)
                    .addComponent(btnRect, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCircle)
                    .addGap(120, 120, 120)
                    .addComponent(btnMove)
                    .addGap(27, 27, 27)
                    .addComponent(btnErase)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                    .addComponent(chbIsFill)
                    .addGap(42, 42, 42))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void btnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineActionPerformed
        curAction = ActionType.Draw;
        curShape = ShapeTypes.Line;
        p1 = p2 = p3 = null;
        pArr.clear();
    }//GEN-LAST:event_btnLineActionPerformed

    private void paintPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseClicked
        switch (curAction) {
            case Draw:
                switch (curShape) {
                    case Line:
                        if (p1 == null) {
                            p1 = new Point(evt.getX(), evt.getY());
                        } else {
                            p2 = new Point(evt.getX(), evt.getY());
                            Line l = new Line(p1, p2, curBorderColor);
                            myArea.addShape(l);

                            p1 = p2 = null;
                        }
                        break;
                    case Rectangle:
                        if (p1 == null) {
                            p1 = new Point(evt.getX(), evt.getY());
                        } else {
                            p2 = new Point(evt.getX(), evt.getY());
                            Rectangle r = new Rectangle(p1, p2, curBorderColor, curFillColor);
                            r.isFilled = chbIsFill.isSelected();
                            myArea.addShape(r);

                            p1 = p2 = null;
                        }
                        break;
                    case Circle:
                        if (p1 == null) {
                            p1 = new Point(evt.getX(), evt.getY());
                        } else {
                            p2 = new Point(evt.getX(), evt.getY());
                            Circle c = new Circle(p1, (int) p1.distance(p2), curBorderColor, curFillColor);
                            c.isFilled = chbIsFill.isSelected();
                            myArea.addShape(c);

                            p1 = p2 = null;
                        }
                        break;

                    case Square:

                        break;
                    case Oval:

                        break;
                    case Triangle:

                        break;
                    case Polygon:

//                        pArr.clear();
                        break;
                }
                break;
            case Move:
                if (p1 == null) {
                    p1 = new Point(evt.getX(), evt.getY());
                } else {
                    p2 = new Point(evt.getX(), evt.getY());
                    myArea.moveShape(p1, p2.getX() - p1.getX(), p2.getY() - p1.getY());
                    p1 = p2 = null;
                }
                break;
            case Erase:
                p1 = new Point(evt.getX(), evt.getY());
                Shape s = myArea.getShapeByPoint(p1);
                if (s != null) {
                    myArea.removeShape(myArea.indexOf(s));
                    myArea.reDrawAll();
                }

                break;
            case ZoomIn:
                break;
            case ZoomOut:
                break;

        }

    }//GEN-LAST:event_paintPanelMouseClicked

    private void btnRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectActionPerformed
        curAction = ActionType.Draw;
        curShape = ShapeTypes.Rectangle;
        p1 = p2 = p3 = null;
        pArr.clear();
    }//GEN-LAST:event_btnRectActionPerformed

    private void btnCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircleActionPerformed
        curAction = ActionType.Draw;
        curShape = ShapeTypes.Circle;
        p1 = p2 = p3 = null;
        pArr.clear();
    }//GEN-LAST:event_btnCircleActionPerformed

    private void btnMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveActionPerformed
        curAction = ActionType.Move;
        pArr.clear();
        p1 = p2 = p3 = null;
    }//GEN-LAST:event_btnMoveActionPerformed

    private void btnEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraseActionPerformed
        curAction = ActionType.Erase;
        pArr.clear();
        p1 = p2 = p3 = null;
    }//GEN-LAST:event_btnEraseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Parsa Es
    private JPanel paintPanel;
    private JButton btnLine;
    private JButton btnRect;
    private JButton btnCircle;
    private JButton btnMove;
    private JButton btnErase;
    private JCheckBox chbIsFill;
    // End of variables declaration//GEN-END:variables
}
